### ISSUE TITLE
Adapt bridge pattern to create a graph

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1067]
# Issue

There are number of ways to run a graph 📦 
There are also number of ways to load a graph  📟 

This makes 📦 x 📟 ways to load and run the graph.

# Proposed Idea

we define a bridge, named as a compiler ☄️ to make run and load 📦 + 📟 

# Evolution Path & Action Plan

1. Prepare Classes
   - [ ] Compiler & interpreter #1067
   - [ ] Common Graph Representation #1067
   - [ ] Graph Data Structure
   - [ ] Graph Interface & Mock Graph
   - [ ] Frontend Interface & Mock Frontend
   - [ ] Backend Interface & Mock Backend
   - [ ] Actual Compiler
1. Scalable graph node (Node IR)
   - [ ] Node as a list of properties (which will have it's own frontend handler.. #400)
   - [ ] Apply only for the fc layer (possibly a bit more...)
1. Simple Ini test run
   - [ ] InI Frontend (realization happens here)
   - [ ] InI Backend (compilation happens here)
1. Tflite Output #899 
   - [ ] Prepare for the flatbuffer
   - [ ] Add Tflite backend 
1. Tflite Input #898 
   - [ ] Add Tflite backend
1. Expand to other layers

# Pitfalls Not Fully Considered Yet. (but will/must be handled)

- [ ] Memory layout of the buffer (I think we can have a WeightLoader * when we compile, or each weight will save the dependency I guess)
- [ ] There is a 1:n mapping of a type. This should be flattened (eg loss, pooling, activation...)
