### ISSUE TITLE
Memory optimization for Training and Inference

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1127]
Memory optimization done by the manager works well for a sequential model. However, it does not work very well with model with multiple inputs and outputs (like resnet, etc). 
Memory optimization needs to
1. work with the graph than working with topologically sorted version of it
2. Memory optimization needs to use producer-consumer model, the producer is the GraphNode making the output, and consumer is the node which consumes that tensor as an input. With producer-consumer modelling, a tensor once produced must stay alive till its consumer has not consumed it.

**Comment by kparichay** [comment]
More details are required to avoid fragmentation of memory in the common memory pool. Will add these details soon.

**Comment by jijoongmoon** [comment]
In oder to do it, we need to check if we can get the multiple input and multiple output. That means multiple loss. So far,  we didn't considered it. I guess, we also need to support run the inference with multi-threaded ( not layer level, I mean graph level ). Then, the memory management will be more complicated.

**Comment by kparichay** [comment]
For each layer operation, we create a buffer lifespan object containing start time, and end time.
- start time: the buffer must be available for use for this time
- end time: the buffer has been consumed at this point and is available for reuse
The time is set based on the topological sorting of the layers to be run. For example, consider a 3 layer model, L1 (fc layer), L2 (fc layer), and L3 (addition layer). So, in this case:
- L1 executes from time 0 to 1: In1 is the input buffer (start:0, end:1), out1 is the output buffer (start:1, end:3)
- L2 executes from time 1 to 2: In2 is the input buffer (start:1, end:2), out2 is the output buffer (start:2, end:3)
- L3 executes from time 2 to 3: out1 and out2 is the input buffers (start:1, end:3 for out1 and start:2, end:3 for out2), out3 is the output buffer (start:2, end:3)
In this case, we have 4 buffers with their lifespans set. Once we get lifespans in general for all input/output buffers, the memory optimization has been reduced to an interval overlap problem, which is easy to solve with a memory pool.

**Comment by kparichay** [comment]
For expanding the above for training, assume a backwarding graph expanded outward, and backwarding can be assumed to be like forwarding with extra buffers (for gradients/derivatives), and same memory optimization will work for backwarding as well.

**Comment by kparichay** [comment]
Preparation:
1. Given a GraphNode, get access to the corresponding input GraphNodes, output GraphNodes, its index in the sorted list of nodes (which is the time for execution)
2. Given tensor, create a map from tensor to its usage list. Each usage of each tensor must be added to this list. For example, given two nodes, A -> B, output tensor of node A (same as output tensor of node B) will add its usage with Time Idx 1 and Time Idx 2. Life span of a tensor will be the full range of the usage of a tensor.

I will clarify any confusion between tensor and memory sharing. At this point, this discussion will not worry itself with memory sharing, but only with tensor sharing. In tensor sharing, the tensor with its inputs and outputs are shared. In the above example of node A & B, input tensor of node A and output tensor of node B are shared.

The manager will also contain an interface to request memory as below
```
int requestMem(size_t bytes, unsigned int start_time, unsigned int end_time); // get identifier for a memory
void *allocMem(int identifier); // allocate memory for the identifier
```
This will return a memory of size bytes, which can be used between start_time and end_time. Usage outside of this time will result in UB. The sharing of the memory will be done within this interface (which will be discussed at the end).

Once the above two structures are made and interface ready, the manager can easily identify which tensors are required when, and simply request the memory for each tensor based on the range of each tensor usage. 

Memory Sharing: Given a start_time and end_time, the manager can identify the overlaps based on the intervals over which the bytes of memory is required. There will be 3 patterns of memory:
1. valid for 1 unit time - required for only forward, only backward. one such example is gradient.
2. valid for short unit time - derivatives while training, inputs/outputs for inference
3. valid for long unit time - inputs/outputs while training
4. valid for all time - weights
The memory allocation will done based on these cases. Case 1. and 4. are trivial.
However, cases 2. and 3. will require some heuristics to minimize fragmentation.

**Comment by zhoonit** [comment]
I have one suggestion in addition.

Could we make an abstraction over those instead of directly appling this to a graph? like a callable `Startegy` class or so.

So we that we can decouple the optimization techniques from the graph itself? (which there might be whole different way should be applied, say, to boost the speed).

**Comment by kparichay** [comment]
I didn't mention details on this part:

1. There will be a base `memoryAllocator` class, which will provide the interface of `requestMem` and `allocMem`. Providing different types of memory for different backend would mean overriding the class to provide different strategies of allocation.
2. Inside each class, there will be a `planner` or a `strategy` object passed on construction which will be used to decide how the memory can be reused.

The purpose of simplifying the disconnecting the interface of `requestMem` and `allocMem` with tensor and graph is to be able to support various backends and planner classes.

**Comment by kparichay** [comment]
TODOs from VCC:
1. **valid time - what start to end time is the contents of the tensor going to stay valid** - add this information per tensor
2. Split the backward time step to two parts - gradient and derivative - so that derivative memory sharing can be done
3. Consider about the run-time optimization where the layer developer give information about the release of the tensor

**Comment by kparichay** [comment]
- [ ] Support Memory pool with a basic memory planner - completed with #1479
- [ ] Support execution order and lifespan for tensors - completed with #1489
- [ ] Support Tensor pool for tensor requests - completed with #1511
- [ ] Update manager to use the new memory management setup for all its tensors requests - completed with #1522
- [ ] Support optimizer memory planners
- [ ] Benchmarking of all the planners with Resnet, VGG and LeNet (possibly with an RNN as well)
- [ ] Support choosing the best memory planner based on their own requirements

**Comment by kparichay** [comment]
Benchmarking models with memory optimizations:

|  | VGG | ResNet18 | LeNet |
|---|---|---|---|
| Basic Planner | 885 | 246.5 | 3.8 |
|  |  |  |  |
|  |  |  |  |

The table notes the peak heap memory consumption for various models in MB. The models are each present as `Applications`.
Note that the above values are generated using https://github.com/KDE/heaptrack, and do not reflect the peak RSS.
