### ISSUE TITLE
Additional CI maintanence

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1235]
These are low priority jobs for ci.

- [x] [update daily-build badge](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-anonymized-urls#an-image-that-changed-recently-is-not-updating)
- [x] delete outdated daily build
- [ ] migrate coverage report to airflow
- [ ] migrate to a legit database

**Comment by zhoonit** [comment]
There are some undone work but it's low priority and likely to stale so closing
