### ISSUE TITLE
Enable launchpad build

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1251]
Enable launchpad build  for both bionic and focal:
- [x] update debian packaging #1236 
- [x] update install filenames for the API #1246 
- [x] set common tolerance for the unittests to pass on launchpad #1248
- [x] lower tolerance further just for debian builds

Do not close this issue till the launchpad build succeeds.

**Comment by kparichay** [comment]
All builds pass except armhf bionic.

**Comment by zhoonit** [comment]
Wonder if we can close this?

**Comment by kparichay** [comment]
armhf bionic still fails.

**Comment by zhoonit** [comment]
Sad
