### ISSUE TITLE
Support attention layer

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1599]
- [x] Support basic attention layer with query and value
  - [x] Support forwarding and setup - #1600
  - [x] Support backwarding - #1602
- [x] Support attention layer with query, key and value #1613
- [ ] Add unit tests for the same - Done - added within each PR.
- [ ] Extend to support MoL attention layer - https://arxiv.org/pdf/2009.02725.pdf
