### ISSUE TITLE
Provides C++ API

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#199]
We have to provides C++ API

**Comment by myungjoo** [comment]
For C++ APIs, you need to communicate with SNAP people.

**Comment by kparichay** [comment]
- [ ] Cleanup existing headers (to allow to expose these directly)
- [ ] Align the API with SNAP people
- [ ] Move various functions to protected and declare classes as friends - then the classes can be directly exposed

**Comment by kparichay** [comment]
@jijoongmoon Close this issue?
