### ISSUE TITLE
Tizen ACR

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nntrainer#259]
### Add nntrainer to OBS project ###
* Jira: https://bugs.tizen.org/browse/TRE-2498
* status: Done

### Add nntrainer package to Tizen Platform Image ###
* Jira: https://bugs.tizen.org/browse/TRE-2501
* status: Done
* http://download.tizen.org/snapshots/tizen/unified/tizen-unified_20200710.1/

### Add rule file for Coverity / Svace Component
* PR: https://github.sec.samsung.net/RS-SA/tizen-components/pull/140
* status: Done

### ACR for ML training APIs
* Jira: https://code.sec.samsung.net/jira/browse/ACR-1579
* status: API review

**Comment by zhoonit** [comment]
migrated from #419

## ACR requirements
- [x] Add tizen feature check #421 (@kparichay)
- [ ] Add tizen privilege check (@kparichay)

## TCM 
- [x] Meet tcm requirements
- [ ] Make a report and request for verification & validation

## TCT
### UTC
- [x] Add scaffolding
- [ ] Add tcs
- [ ] reviews (gerrit link: TBD)

### ITC
- [ ] Make an example(#342)
- [ ] Update readme.md(#410)

## Doc
- TBD...

**Comment by zhoonit** [comment]
status update. UTC/ITC's are merged. docs are under review
