### ISSUE TITLE
Data Buffer refactor

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#303]
Implementation of data buffer needs quite some refactoring.

**Comment by zhoonit** [comment]
As discussed offline, I am taking this issue

- [ ] Make a class that manages one buf type & current databuffer wraps around the class.
- [ ] Fine grained buffer (validation) states 
- [ ] Change vector to a struct containing void *, size and return

**Comment by kparichay** [comment]
@zhoonit It is desirable for databuffer to use tensor to allocate the memory. However, any other dependency onto tensor is not required as databuffer just treats memory as void * with bytes size.
Also, when refactor, please make some space for adding multiple parallel thread readers (in future, if not now).

**Comment by zhoonit** [comment]
- related bugs #1322

**Comment by kparichay** [comment]
Track https://github.com/pravega/gstreamer-pravega/issues/83

**Comment by zhoonit** [comment]
Backlogging some undone works:

- [ ] Change property of the random data generator. 
- [ ] finalize return size as well.
- [ ] DataProducer::generator returns single element than batch (check if this is okay with tizen)
- [ ] change semantics of DataProducer::size()
- [ ] change signature of DataProducer::generator

**Comment by zhoonit** [comment]
Add interrupt mechanism for the startFetchWorker

**Comment by zhoonit** [comment]
There can be more PR's as per upcoming reviews, but #1510 is the planned last patch of the work.

**Comment by zhoonit** [comment]
We have a mt support issue with less complicated locks left
