### ISSUE TITLE
Upgrade Tensor in NNTrainer

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#348]
Tensor is the key base stone of nntrainer. Most of the features are implemented on top of this.
There are several optimization items to be done.
- [ ] refactor of tensor to support different type of hardware accelerator
- [ ] Extend tensor feature
   - [ ] Make a tensor equal operation ( #202 )
   - [ ] Tensor copy constructor (#281)
   - [ ] Support multiple data type - template data type (#321)

- [ ] Performance Optimization
   - [x] Check open blas implementation
   - [x] Try to use openMP
   - [ ] Try to use ACL

**Comment by zhoonit** [comment]
- [ ] use allocator in Tensor #332

**Comment by jijoongmoon** [comment]
close and make new issues for each of them
