### ISSUE TITLE
Support models as Graph

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#349]
We need to graph optimization to describe and optimize layers better.
- [x] Optimize ini description (#239)
    - [x] support skip connections #469
- [x] DAG ( Directed Acyclic Graph ) (#346)

**Comment by kparichay** [comment]
@jijoongmoon RNN can be supported with just DAG. DCG is needed just for backward connection at the model level.

**Comment by kparichay** [comment]
Support DAG - 
- [ ] Create TensorOps class
  - [ ] Layer extends TensorOps class
  - [ ] Update SharedTensor to include the number of tensors
  - [ ] Update signature of forward and backward, split applyGradients to be able to use in graph directly
- [ ] Choose backend library for graph
- [ ] Create a graph in model, with optimizer 
- [ ] Pass forward and backward arguments to graph and create entries in graph
- [ ] Store all the ops and tensors in a separate list
- [ ] Initialize ops in model.compile
- [ ] Initialize ops (allocate memory) in the first run
- [ ] Use topological sort for starters
- [ ] Modify topological sort to allow running multiple nodes in parallel

**Comment by jijoongmoon** [comment]
done with #712

**Comment by kparichay** [comment]
Lets track the TODO here and close this issue later once all graph related things are done (or close after #712 is merged).

[TODO](https://github.com/nnstreamer/nntrainer/pull/712#issuecomment-731894632)
  
- [ ] After make node list of graph, we have to find root. (That means it should be the only one input for now.).
      Need to support multiple input and support search.
- [ ] unordered_map ( I'm not sure though )
- [ ] More Unittest 
- [ ] Proper Example ( for now mini resnet is tested with one iteration )
- [ ] Check Making Graph with API (C and C++) for non-ini initialization
- [ ] etc.
