### ISSUE TITLE
Extend supported layers

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#351]
- [ ] Vision related layer
  - [ ] Support Conv2D Transpose Layer
  - [ ] Support Depthwise Conv2D Layer
  - [ ] Support Conv1D Layer (#197)
  - [ ] Support Pooling1D Layer (#198)

- [ ] Recurrent Network
  - [x] Skip connection
  - [ ] RNN (#195)
  - [ ] LSTM (#196)
  - [ ] GRU
  - [ ] ELU

**Comment by jijoongmoon** [comment]
close and make issues separately
