### ISSUE TITLE
[ Proposal ] refactoring nntrainer

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#355]
- [x] Make a discussion (#95)
- [x] Refactor Tensor
     - [ ] Support delegate
- [x] Support Graph (DAG) -> Add graphNode and support for graphnode (@zhoonit #346 )
     - [x] skip connection
- [x] Custom Layer? (haven't discussed yet. AKAIK from @zhoonit )
- [x] Hierarchical Optimizer Class (will be tracked with #404 @zhoonit )
- [x] Hierarchical Activation
etc.

**Comment by jijoongmoon** [comment]
close and make new issues.
