### ISSUE TITLE
Refactor plans for negative cases

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#374]
#### Add way to check applications 
- [x] Add automated test to check sanity of applications (#375)
  - [x] returns 0 for proper input (positive test)
  - [x] ~returns 0 for inproper input (negative test)~ (cancelled for now)
  - [x] ~ensure that output does not change (maybe?)~ (cancelled for now)

#### Add validation
- [x] resolve undefined behavior of network::init and enable negative ini cases (#316) (#384)
- [x] use delegates strategy for checkValidation(#387) -> postphoned and closed in this umbrella

#### Prune unnecessary functions / variable
- [x] Delete cost, bn_follow from layer.h (#384)
- [x] Unify optimizer initialize to have only params (#381)
- [x] ~add validation initLossLayer~ (Done in `neuralnet::init`)
- [x] change exception::invalid_property -> exception::not_supported (#380)

#### Minor refactors as well
- [x] Delete VERIFY_SET_DIMENSION (#384)
- [x] is_file_exist -> isFileExist (#384)

**Comment by zhoonit** [comment]
Project done, waiting for review and merge

**Comment by zhoonit** [comment]
will be closed when #393 is merged
