### ISSUE TITLE
Bugs from more negative cases

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#388]
## descriptive debug logs
- Add more log debug to get better information

## bugs
- [x] Activation layer itself is making activation again (#390) (#429)
- [x] reset neuralnet when it failes to load (#382) (#413)
- [x] init_loss_layer should fail when cost is unknown (with different log)
- [x] buf size is determined after minibatch size is set so buf size can be smaller than minibatch (#389)
~ - [ ] loadNetworkConf ignores invalid values from ini (#391) ~ (dropped from the umbrella)

**Comment by zhoonit** [comment]
Closing this as all of the issues have been resolved except for dropped one.
