### ISSUE TITLE
Add property handler

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#404]
This Issue tracks migration to property handler starting from #400 

- [ ] Add property handler(#400)
- [ ] Add single property test(#400)
- [ ] Add multiproperty test
- [ ] Implement Properties::load
- [ ] Implement load test
- [ ] Migrate layer to use `Properties`
- [ ] Change optimizer to inherit
- [ ] Migrate optimizer to use `Properties`

------- related bugs
- [ ] load network conf ignores invalid value(#391)

**Comment by kparichay** [comment]
Just adding this here
- [ ] Migrate all `enum` to `enum class` unless directly connected with C-API.

**Comment by kparichay** [comment]
@zhoonit with this, if my understanding is correct, the properties string will be available with the prop_traits. So, also adding to update `parse_util` to just use enum count than string of array for parsing to avoid bugs like this - https://github.com/nnstreamer/nntrainer/pull/402#discussion_r464763038
- [ ] Update `parse_util` to use `prop_traits.serialize()` with enum count than storing the string values.

**Comment by zhoonit** [comment]
Property handler is done with #1033
