### ISSUE TITLE
Make missing piece of neuralnet print

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#423]
Below list should be done.

- [ ] print neuralnet property
- [ ] print optimizer (with print optimizer prop)
- [ ] print loss function when it is not initialized. (if it is initialized, loss layer will be printed)
- [ ] Add status to check neuralnet has been run. (issue #290)
- [ ] print neuralnet metric after it is run
