### ISSUE TITLE
Create a transfer learning application

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#451]
Create a transfer learning application with C-API for reference to our customers, as this will be the primary use case of our library.

**Comment by kparichay** [comment]
- [ ] Add testing to the application #549
- [ ] Update to use C-API #556
- [ ] Add tensorflow to tflite model conversion to README.md #555
