### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#46]
README.md is kind of out of date. Need to update.

**Comment by zhoonit** [comment]
- [ ] Introduce architectural overview  (if possible)
- [ ] Introduce how to build
- [ ] getting started (run the example)

**Comment by jijoongmoon** [comment]
close (#452)
