### ISSUE TITLE
Add model test for integrated layers with many epochs

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#544]
Make testbed for multi layers with loss and many epochs to match with other frameworks.

- [x] Open up a `NeuralNet::getFlattenLayer` (#641)
- [x] Make a reference generator (#661)
- [x] Make a test generator (#642)
- [x] Make mnist to test (#708 )
- [x] Make arbitrary tests (not done but ready)
- [x] Restructure generator script (from #642) (#669)
  - Move shapes and filename to run script
  - Add from_logit arguments
