### ISSUE TITLE
Update customshortcut to inference

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#553]
- [x] update a gui for the inference
   - [x] Change router to add inference (#571) (#580)
   - [x] Add visual queue when training is done (Add/handle signals) (#572) (#595)
   - [x] Prohibit to press back button when training (#573) (#594)
   - [x] Add go to main menu (#574) (#595)
   - [x] Add view of infer result page (#612)
   - [x] Update view of infer result page (#614)
- [x] add inference feature to the app (#612)
   - [x] Input data
   - [x] Make a single inference
- [x] extras
  - [x] filter dependency issue (#616)
  - [x] figure out what slows down the training (#611) (#626)
  - [x] not use png (#627)
  - [x] make emoji even bigger (#631)
  - [x] update readme (#635)
  - [x] add cutoff logic (#634)

**Comment by zhoonit** [comment]
This issue has been finished as of #635
