### ISSUE TITLE
On-device specializations (next year)

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#615]
Below are certain optimizations to be done from the on-device perspectives (for next year):
1. Memory optimizations
  - [ ] Memory to be allocated only at train/validate/test time. Once the training function returns, all memory to be released.
  - [ ] Memory allocated with train should peak with the model memory, input/output memory and data buffer memory. Extra overhead memory must be minimized.
  - [ ] Memory must allocated be at the first iteration of training, and then the memory must be reused than allocating more memory.
  - [ ] A new `max_memory` user-defined parameter which limits the memory available for training. If our training model cant fit in memory,
    - [ ] Accumulate gradients over smaller batches. 
    - [ ] Free the memory of the layer after certain computation if the result is not needed in backwarding. Then re-allocate that memory in the next iteration, to limit the peak memory requirement.
    - [ ] In extreme cases, store the variable to disk and read back when needed.

2. Performance optimizations
  - [ ] Support Eigen library as a backend
  - [ ] Thread optimizations:
    - [ ] Graph must identify the layers/operations which can be done in parallel

More performance optimizations will be added.

**Comment by zhoonit** [comment]
Can we use Eigen? If we can and plan to move, we should better have a similar interface to ease the migration.

**Comment by kparichay** [comment]
I think Eigen will be supported, but not necessary. For the internal interface to support different backends, I guess it can be handled later this year.

**Comment by jijoongmoon** [comment]
> I think Eigen will be supported, but not necessary. For the internal interface to support different backends, I guess it can be handled later this year.

I don't think we are using exactly Eigen though. Well may be part of it but we are going to use NNFW Runtime Compute and I guess it has Eigen and other libs. We have to discuss about it with NNFW Team cause they are not ready to make use it. So let's not be sure about it. We still need to discuss about it.
