### ISSUE TITLE
Simplify transfer learning application

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#660]
The most basic transfer learning application is very complicated because nntrainer does not support specifying backbone from the API. Rather, the user is expected to handle all of it themselves.

Basic support:
- [ ] Support backbone to be specified as a filename in ini file
  - [ ] If this is a tensorflow-lite file, run tflite on the input data first before giving the input to nntrainer
    - [x] support with nnstreamer #683 
    - [x] support directly with tflite to allow easier support on Android #693 
    - [ ] Update transfer learning/other applications to use these backbones #693 #729 
  - [x] If this is nntrainer file, load nntrainer layers and preprend them to the current nntrainer graph - #665

Advanced support: 
- [x] Nested backbones -  #665
- [x] Multiple backbone -  #665
- [x] Allow trainable/non-trainable - #667
- [x] Other frameworks backbone - use nnstreamer single API to run these #683
- [ ] Support backbone specific features from https://github.com/nnstreamer/nntrainer/issues/660#issuecomment-716313854 - #726
- [ ] Support caching the outputs of backbone as that part of the model is fixed. - postponed.
- [ ] backbone conversion - if tflite model file is provided, but that backbone needs training, load weights from tflite backbone to nntrainer and treat it as nntrainer backbone. - postponed.

More advanced support to be added.

**Comment by kparichay** [comment]
Sharing design here which @zhoonit described in an offline meeting earlier:

```ini
[Model]
backbone : filename.${ext}
```
Extensions - ini (handled with nntrainer), tflite/etc (handled with external frameworks)

Note: 
In the existing ini file design, as `Model` does not have a type, for now, defining multiple models to modularize the model declaration was not possible. However, with the backbone, we can make a modular model block and then use it again and again as shown below.

```ini
# resnetblock.ini
[Model]
# Define the resnet block here

....
[InputLayer]
...
[Conv1Layer]
...
[Conv2Layer]
...
[Conv3Layer]
...
[Conv4Layer]
...

```

And then in the model ini, use the block backbone to describe the model modularly.
```ini
[Model]
# Define the resnet model here

....
[InputLayer]
...
[Block1]
backbone=resnetblock.ini
...
[Block2]
backbone=resnetblock.ini

[Pooling2dLayer]
...
[Block3]
backbone=resnetblock.ini
...
[Block4]
backbone=resnetblock.ini
...

[FCLayer]
...
```
This does not support specifying a different number of channels which are needed by resnet blocks in general, but this is a start. 
Parameterized ini file is something to think about.

**Comment by kparichay** [comment]
Below allows choosing a small subsection of the model as backbone than the whole model.

```ini
[block1]
backbone: backbone1.ini
InputLayer: ${INPUT_LAYER}
InputShape: ${INPUT_SHAPE}
OutputLayer: ${OUTPUT_LAYER}
ScaleSize: FLOAT
```

InputShape is needed (when specifying InputLayer) if the shape of InputLayer cannot be interpreted.
This can be later extended to multiple inputs/outputs but for now, it will be limited to single input/output.
ScaleSize would be used to scale the number of channels/number of units for conv/FC layer correspondingly.
