### ISSUE TITLE
Add appcontext

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#716]
We need to save runtime app configuration (work as a session, profile...).

Let's start with saving the current working directory, later registering available :whale: (layers, optimizers....)  type will be added

First thing that will be done is...
- [x] Design #728
  - [x] add header
  - [x] add basic ~mock~ tests
  - [x] add implementation
- [x] Basic working
  - [x] Current working directory #728
  - [x] wire app context to model #733
- [x] Register factories
  - [x] register built-in objects #745
     - [x] change factory function spec #745
  - [x] test with optimizer
     - [x] change opt enum type to string #721
     - [x] try register custom optimizer #745
     - [x] add createObject function to adam and sgd #746
     - [ ] ~Add (sort of) virtual copy constructor~ Canceled as waiting for ccapi refactoring
     - [x] register built-in optimizer #746
  - [x] apply the behavior to the layers 
     - [x] change layer type enum to string #725 
     - [x] add createObject funtion to each object #753 
     - [x] register built-in layers #753 
- [x] Dynamic loading support
  - [x] Add dynamic loader (resolving path and other stuff..) (#908)
  - [x] Add dynamic registerer format (with defined symbols for constructor, destructor) (#908)
  - [x] Add plugin loader (get path from conv, env) (#915)
  - [x] Add documentation (#915)
- [x] Demonstration
  - [x] Add separated custom layer (say, pow2) (#779)
- [ ] CAPI support (need discussion, nothing has set yet)

**Comment by kparichay** [comment]
Can you expand a little on this context about its purpose - creating a global session would require passing that session everywhere internally and externally, which is not convenient.

**Comment by zhoonit** [comment]
This is to add a configuration about additional (and dynamic) setup.

This is to resolve #370 and support registering a customized layer and setting up a LOG_DIR, possibly others (like LOG_DEBUG_LEVEL)..

I am thinking code like below, I am open to design suggestion :)

```cpp
init_global_context(void) __attribute__((constructor)); # initiate and configure singletone instance for nntrianer::AppContext::Global

fini_global_context(void) __attribute__(destructor)); 

int main() {
# If want to use custom context
  NNTrainer nntr = new nntrainer::AppContext();
# if want to use global configuration
  NNTrainer nntr = nntrainer::AppContext::Global();
#
 
  nntr.setWorkingDirectory("/path/"); # to resolve #370 
  nntr.setLogDirectory("/path/");

  nntr.register_layer("custom", CustomLayer);
  nntr.register_optimizer("custom_opt", CustomOptimizer);

  createModel(model, global_context=nntrainer::AppContext::Global());
}
```

**Comment by kparichay** [comment]
How is AppContext different from the model itself.

```cpp
int main() {
  createModel(model);
  model.addDynamicLibPaths("/path/"); // or with env variable
  model.setLogPath("/path/");
  model.setSavePath("/path/");

  model.register_layer("custom", CustomLayer);
  model.addLayer(std::make_unique<CustomLayer>());
  model.addLayer("custom", CustomLayer);
  model.register_optimizer("custom_opt", CustomOptimizer);
}
```

Registering layers/optimizers to a context creates issues that now the context must also be saved/shared among multiple models and creates more things to do from the user. Rather, if the model is assumed to be the global object which encapsulates everything, then those issues. Yes, with multiple models, custom layers/optimizers will have to be registered multiple times with each model (it's an overhead) but saves providing context everywhere.

Register functions can be outside models for nntrainer directly which affects the core nntrainer like below:
```cpp
int main() {
  createModel(model);
  model.addDynamicLibPaths("/path/"); // or with env variable
  model.setLogPath("/path/");
  model.setSavePath("/path/");

  nntrainer::register_layer("custom", CustomLayer);
  model.addLayer(std::make_unique<CustomLayer>());
  model.addLayer("custom", CustomLayer);
  nntrainer::register_optimizer("custom_opt", CustomOptimizer);
}
```

**Comment by zhoonit** [comment]
When a user is creating a custom layer or optimizer, she won't be able to access the savePath or other configurable variable if we are to set those variable inside a (global) model. If we have a context parameter, user can access it because it will be evaluated in lazy fashion.

> Register functions can be outside models for nntrainer directly which affects the core nntrainer like below:
The core idea of making AppContext is accessing the core nntrainer without any object declared in global space and everyone accessing it. Creating another session is more of an additional functionality as of now.

`nntrainer::register_layer("custom", CustomLayer, context=Global_context())`  or we can have `nntrainer::register_layer("custom", CustomLayer") as a synthetic sugar.

> but saves providing context everywhere.
This will default to the global context so, it won't create an overhead if the user is not customizing anything but leaving room to customizing it.

**Comment by kparichay** [comment]
> When a user is creating a custom layer or optimizer, she won't be able to access the savePath or other configurable variable if we are to set those variable inside a (global) model. If we have a context parameter, user can access it because it will be evaluated in lazy fashion.

These variables are meant for the layers/optimizers. They are meant for the model. These custom objects are supposed to receive the file objects (processed objects) than direct values provided by the user.

> The core idea of making AppContext is accessing the core nntrainer without any object declared in global space and everyone accessing it. Creating another session is more of additional functionality as of now.

The core idea is good, but this is usually required when in the global space things are being over-written (example - user wants to create multiple layers with the same name) or overhead is coming on, but I don't see either being an issue in nntrainer.

> This will default to the global context so, it won't create an overhead if the user is not customizing anything but leaving room to customizing it.

This creates the issue that the model file is not complete itself anymore. It needs to be paired with the appropriate context file which just complicates things.

**Comment by zhoonit** [comment]
> These variables are not meant for the layers/optimizers. They are meant for the model. These custom objects are supposed to receive the file objects (processed objects) than direct values provided by the user.

I think we are not sure at this stage if we need configuration for layers as well, say, if we have to restrict num threads globally or force it to cpu for debuging purpose? allow fused operations? setting debug level for a specific layer? Those can be done by passing a variable from a model, and it will couple model and layer, those changing layer spec will tackle model method as well. More or less, this is more flexible than only model having such configuration members.

> This creates the issue that the model file is not complete anymore by itself. It needs to be paired with the appropriate context file which just complicates things.

1. From the user's point of view, nothing will be changed if user won't customize anything so nothing is more complicated for the user.

2. This encapsulates a configuration to an object and model can `have` the configuration (or function can `use` as an argument), which is less complicated and more orthogonal than having n members for each model. 

for example, `addDynamicPathLib` should be at the same level as `register_layer`, let's say if we are running two models and model add dynamic path lib?

**Comment by zhoonit** [comment]
If you worry about it is complicating the user's code.
How about model has a context member? We can think of it as a bunch of member variables packed inside a configuration class. Only leaving flexibility to extend. 


```cpp
class Model {
public:
  Model(AppContext ac_ = AppContext::AppInstance(), other members...): app_context(ac_){
  }
}

**Comment by zhoonit** [comment]
We had an offline discussion to make appcontext but restrict its usage to be a member of Model for now and later decide details later

**Comment by zhoonit** [comment]
Now this is done except for the capi support. I'll make a separate issue for the capi support to keep it simple.
