### ISSUE TITLE
Create a graph attribute

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#774]
To manage graphs and layers better, make a graph attribute.
`GraphAttr` will maintain all the layer list, input and output list, and weight list. It only contains essential parts of the graph. Sorted lists etc will not be part of it.

- [x] `GraphAttr` will be passed to a layer `initialize()`, where layer would call `graphAttr.registerWeight()` to add a weight.
This will allow the graph to manage all the weights. This is crucial for #766, and create a good interface for the custom layer to manage their weights.
The advantage of passing `GraphAttr` than the whole `Graph` to the layer is for the security purpose in the case of a custom layer. - #782

- [x] Similar interface will be there for inputs and outputs - `graphAttr.registerInput()` and `graphAttr.registerOutput()`. - #827

- [x] Calling these functions multiple times would register multiple weights/inputs/outputs. From the graph perspective, all the layer related information can now be handled together, simplifying graph code. - #827

- [x] Further, `graphAttr` will also have `optimizer` inside it. `registerWeight()` internally will also register optimizer related parameters for it (optimizer is known by then as the layer is being initialized). So, optimizer parameters will also be owned by the `graphAttr` as well unifying all the memory at one place. With this, each layer does not need its own optimizer copy. - #786

- [x] Lastly, the weight regularization will move out of each layer will directly be handled by the graph just like optimizer. - #762

**Comment by kparichay** [comment]
The graph attribute came out to be a tensor manager, which manages all the tensor weights.
Graph manages at the layer, and each of those layers interacts with the manager for all its memory needs.
