### ISSUE TITLE
C++ API and architecture refactor

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#986]
This issue is to track the re-factor of the exposed headers and the C++ API.
This will update the NNTrainer architecture to the class diagram finalized with @jijoongmoon.

- [x] Update internal implementation to use only the methods exposed by those headers and not an internal implementation
  - [x] Remove all friends of layers
  - [x] Manage input/output properties better for layer - track at #1454
  - [x] add unittests for ensureName related  to #1009
  - [x] refactor graph to move graph node related members from layers
    - [x] #1029 
    - [x] consider removing adj lists once compile is done to save some space. - #1049
    - [x] move layers connection related properties out to graph - #1142 #1182
  - [x] tensor constructor to support initialization - https://github.com/nnstreamer/nntrainer/pull/1031#discussion_r597551354 - pointed out by @myungjoo - #1452
  - [x] refactor model loader to allow custom properties #1032 
  - [x] prepare custom loss #1256
  - [x] many more
- [x] Update headers and their interfaces
  - [x] Make c++ api equivalent to c API - done with #1050
  - [x] C++ API must be superset of https://github.com/nnstreamer/nntrainer/pull/1010#discussion_r594866783 or the nntrainer filter must be updated to accommodate with the API. - #1461
  - [x] Make c api directly use c++ API - #1050
  - [x] divide `*_internal` to `*_devel` which will be just an interface and `*_impl` which will be the default implementation. For example, Layer <- Layer_devel <- Layer_impl. - #1426
- [ ] Update packaging and applications correspondingly #1450
